# Site settings

title: Composition in probabilistic language understanding
baseurl: "/ESSLLI-2016"
url: "http://gscontras.github.io/ESSLLI-2016"

# Build settings
markdown: kramdown

exclude:
- node_modules